### ISSUE TITLE
Some names are still cut off

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2016#187]
- Chenise Summer Paquette
- Mystine Laframboise Vien

<img width="328" alt="screen shot 2016-03-01 at 12 26 12 pm" src="https://cloud.githubusercontent.com/assets/105192/13435583/05f20682-dfa9-11e5-922a-c923aa2cda1b.png">

---

Possible solution: allow multiple lines for names:

<img width="322" alt="screen shot 2016-03-01 at 12 26 44 pm" src="https://cloud.githubusercontent.com/assets/105192/13435595/11d95c98-dfa9-11e5-9b8e-39be2d0f9b6c.png">

```css
.ph-student p {
   ...
   bottom: 0;
   padding: 0.4em 0;
}
```
